### ISSUE TITLE
1warning1error

### ISSUE THREAD

**Issue by fengx1a0** [ibukisaar/MD5Gif#1]
![image](https://user-images.githubusercontent.com/74698099/99906208-ca330500-2d10-11eb-93fb-a778fbdf965c.png)
严重性	代码	说明	项目	文件	行	禁止显示状态
警告	CS0162	检测到无法访问的代码	MD5Gif	C:\Users\风潇\Desktop\git\MD5Gif\MD5Gif\Program.cs	401	活动

严重性	代码	说明	项目	文件	行	禁止显示状态
错误	MSB8020	无法找到 ClangCL 的生成工具(平台工具集 =“ClangCL”)。若要使用 ClangCL 生成工具进行生成，请安装 ClangCL 生成工具。或者，可以升级到当前 Visual Studio 工具，方式是通过选择“项目”菜单或右键单击该解决方案，然后选择“重定解决方案目标”。	MD5	C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppBuild.targets	411

**Comment by ibukisaar** [comment]
1. 那个警告是正常的。无法访问的代码是**不生成23333333开头的MD5的代码**，可以通过修改`Program.IsMake23333333MD5`切换分支。
2. 打开**Visual Studio Installer**，点击**修改**，**单个组件**，搜索"**clang**"，安装"**适用于 v142 的 C++ Clang-cl 生成工具(x64/x86)**"。

**Comment by ibukisaar** [comment]
关于那个错误，可以不用安装clang-cl了，我将生成工具改成VS并重新commit了。

**Comment by fengx1a0** [comment]
谢谢师傅，已经运作起来了，请问师傅原来用的什么运行的呢？是VScode嘛

**Comment by ibukisaar** [comment]
我一直都是用Visual Studio 2019的，只不过我更喜欢用clang编译器，所以当时项目设置的是clang-cl。

**Comment by fengx1a0** [comment]
谢谢师傅
